spring:
  application:
    name: procurement-service

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html
    tryItOutEnabled: true
    filter: true

server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: health,info
