spring:
  application:
    name: identity-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:identitydb;DB_CLOSE_DELAY=-1;MODE=MySQL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:sa}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8081

jwt:
  issuer: ${JWT_ISSUER:ToolVault}
  access-exp-min: ${JWT_ACCESS_EXP_MIN:15}
  refresh-exp-min: 4320
  secret: ${JWT_SECRET:b20a0c46f1e64b29b20a0c46f1e64b29b20a0c46f1e64b29b20a0c46f1e64b29}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never